apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bchd-web-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - www.bchd.cash
    - bchd.cash
    secretName: bchd-web-tls
  defaultBackend:
    service:
      name: bchd-web
      port:
        number: 95
  rules:
  - host: bchd.cash
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bchd-web
            port:
              number: 95
  - host: www.bchd.cash
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bchd-web
            port:
              number: 95
